#############################################################################
# Makefile for building: libmac.xpl.dylib
# Generated by qmake (3.0) (Qt 5.4.0)
# Project:  SmoothStick.pro
# Template: lib
# Command: /Users/izne/Qt54/5.4/clang_64/bin/qmake -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile SmoothStick.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DXPLM200 -DXPLM210 -DAPL=1 -DIBM=0 -DLIN=0
CFLAGS        = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.7 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.7 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I../../Qt54/5.4/clang_64/mkspecs/macx-clang -I. -I../SDK/CHeaders/XPLM -I../SDK/CHeaders/Wrappers -I../SDK/CHeaders/Widgets
QMAKE         = /Users/izne/Qt54/5.4/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = mac.xpl1.0.0
DISTDIR = /Users/izne/Documents/SmoothStick/.tmp/mac.xpl1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -flat_namespace -undefined suppress -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.7 -single_module -dynamiclib
LIBS          = $(SUBLIBS)  
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = SmoothStick.c \
		SPU.c 
OBJECTS       = SmoothStick.o \
		SPU.o
DIST          = ../../Qt54/5.4/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt54/5.4/clang_64/mkspecs/qdevice.pri \
		../../Qt54/5.4/clang_64/mkspecs/features/device_config.prf \
		../../Qt54/5.4/clang_64/mkspecs/common/shell-unix.conf \
		../../Qt54/5.4/clang_64/mkspecs/common/unix.conf \
		../../Qt54/5.4/clang_64/mkspecs/common/mac.conf \
		../../Qt54/5.4/clang_64/mkspecs/common/macx.conf \
		../../Qt54/5.4/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt54/5.4/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt54/5.4/clang_64/mkspecs/common/clang.conf \
		../../Qt54/5.4/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt54/5.4/clang_64/mkspecs/qconfig.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt54/5.4/clang_64/mkspecs/features/qt_config.prf \
		../../Qt54/5.4/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt54/5.4/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt54/5.4/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt54/5.4/clang_64/mkspecs/features/default_pre.prf \
		../../Qt54/5.4/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Qt54/5.4/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt54/5.4/clang_64/mkspecs/features/default_post.prf \
		../../Qt54/5.4/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt54/5.4/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt54/5.4/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt54/5.4/clang_64/mkspecs/features/warn_on.prf \
		../../Qt54/5.4/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt54/5.4/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt54/5.4/clang_64/mkspecs/features/yacc.prf \
		../../Qt54/5.4/clang_64/mkspecs/features/lex.prf \
		SmoothStick.pro SmoothStick.h \
		SPU.h SmoothStick.c \
		SPU.c
QMAKE_TARGET  = mac.xpl
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = libmac.xpl.dylib
TARGETD       = libmac.xpl.dylib

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk \
		-mmacosx-version-min=10.7 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET):  $(OBJECTS) $(SUBLIBS) $(OBJCOMP)  
	-$(DEL_FILE) $(TARGET)
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(LIBS) $(OBJCOMP)



Makefile: SmoothStick.pro ../../Qt54/5.4/clang_64/mkspecs/macx-clang/qmake.conf ../../Qt54/5.4/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt54/5.4/clang_64/mkspecs/qdevice.pri \
		../../Qt54/5.4/clang_64/mkspecs/features/device_config.prf \
		../../Qt54/5.4/clang_64/mkspecs/common/shell-unix.conf \
		../../Qt54/5.4/clang_64/mkspecs/common/unix.conf \
		../../Qt54/5.4/clang_64/mkspecs/common/mac.conf \
		../../Qt54/5.4/clang_64/mkspecs/common/macx.conf \
		../../Qt54/5.4/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt54/5.4/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt54/5.4/clang_64/mkspecs/common/clang.conf \
		../../Qt54/5.4/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt54/5.4/clang_64/mkspecs/qconfig.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt54/5.4/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt54/5.4/clang_64/mkspecs/features/qt_config.prf \
		../../Qt54/5.4/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt54/5.4/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt54/5.4/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt54/5.4/clang_64/mkspecs/features/default_pre.prf \
		../../Qt54/5.4/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Qt54/5.4/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt54/5.4/clang_64/mkspecs/features/default_post.prf \
		../../Qt54/5.4/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt54/5.4/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt54/5.4/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt54/5.4/clang_64/mkspecs/features/warn_on.prf \
		../../Qt54/5.4/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt54/5.4/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt54/5.4/clang_64/mkspecs/features/yacc.prf \
		../../Qt54/5.4/clang_64/mkspecs/features/lex.prf \
		SmoothStick.pro
	$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile SmoothStick.pro
../../Qt54/5.4/clang_64/mkspecs/features/spec_pre.prf:
../../Qt54/5.4/clang_64/mkspecs/qdevice.pri:
../../Qt54/5.4/clang_64/mkspecs/features/device_config.prf:
../../Qt54/5.4/clang_64/mkspecs/common/shell-unix.conf:
../../Qt54/5.4/clang_64/mkspecs/common/unix.conf:
../../Qt54/5.4/clang_64/mkspecs/common/mac.conf:
../../Qt54/5.4/clang_64/mkspecs/common/macx.conf:
../../Qt54/5.4/clang_64/mkspecs/common/gcc-base.conf:
../../Qt54/5.4/clang_64/mkspecs/common/gcc-base-mac.conf:
../../Qt54/5.4/clang_64/mkspecs/common/clang.conf:
../../Qt54/5.4/clang_64/mkspecs/common/clang-mac.conf:
../../Qt54/5.4/clang_64/mkspecs/qconfig.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_core.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_declarative.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_enginio.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_enginio_private.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_help.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_location.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_network.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_script.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_webkit.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Qt54/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Qt54/5.4/clang_64/mkspecs/features/qt_functions.prf:
../../Qt54/5.4/clang_64/mkspecs/features/qt_config.prf:
../../Qt54/5.4/clang_64/mkspecs/macx-clang/qmake.conf:
../../Qt54/5.4/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../Qt54/5.4/clang_64/mkspecs/features/exclusive_builds.prf:
../../Qt54/5.4/clang_64/mkspecs/features/default_pre.prf:
../../Qt54/5.4/clang_64/mkspecs/features/mac/default_pre.prf:
../../Qt54/5.4/clang_64/mkspecs/features/resolve_config.prf:
../../Qt54/5.4/clang_64/mkspecs/features/default_post.prf:
../../Qt54/5.4/clang_64/mkspecs/features/mac/sdk.prf:
../../Qt54/5.4/clang_64/mkspecs/features/mac/default_post.prf:
../../Qt54/5.4/clang_64/mkspecs/features/mac/objective_c.prf:
../../Qt54/5.4/clang_64/mkspecs/features/warn_on.prf:
../../Qt54/5.4/clang_64/mkspecs/features/mac/rez.prf:
../../Qt54/5.4/clang_64/mkspecs/features/testcase_targets.prf:
../../Qt54/5.4/clang_64/mkspecs/features/yacc.prf:
../../Qt54/5.4/clang_64/mkspecs/features/lex.prf:
SmoothStick.pro:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile SmoothStick.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

SmoothStick.o: SmoothStick.c SmoothStick.h \
		../SDK/CHeaders/XPLM/XPLMDefs.h \
		../SDK/CHeaders/XPLM/XPLMPlanes.h \
		../SDK/CHeaders/XPLM/XPLMCamera.h \
		../SDK/CHeaders/XPLM/XPLMDataAccess.h \
		../SDK/CHeaders/XPLM/XPLMUtilities.h \
		../SDK/CHeaders/XPLM/XPLMGraphics.h \
		../SDK/CHeaders/XPLM/XPLMDisplay.h \
		../SDK/CHeaders/XPLM/XPLMMenus.h \
		SPU.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o SmoothStick.o SmoothStick.c

SPU.o: SPU.c SPU.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o SPU.o SPU.c

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

